version: '3'
services:
  # Flask app
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app_flask_template
    env_file: docker/app/app.conf
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: always
    ports:
      - '5000:5000'
    networks:
      - app-network

# Docker networks
networks:
  app-network:
    driver: bridge